#!/bin/bash

set data_file   = 'J0252-7104_band4_cald.ms'
set source_name = 'J0252-7104'

mkdir 15_1_SELF_CAL_${source_name}

cd 15_1_SELF_CAL_${source_name}

cp -fr ../${data_file} .

git clone https://github.com/JonahDW/Image-processing.git

git clone https://github.com/hrkloeck/DASKMSWERKZEUGKASTEN.git

git clone https://github.com/hrkloeck/2GC.git

singularity exec --bind ${PWD}:/data /media/scratch/Container_Build/HRK_CASA_6.5_DASK_WSC3.3.1024.simg python3 /data/2GC/Self_calibration_2GC.py /data/ ${data_file}
