#!/bin/bash

set data_file   = 'J0252-7104_band1_cald.ms'

set write_spwd  = "0,1,2,3,4,5,6,7,8,9,10,11,12,13"

singularity exec --bind ${PWD}:/data /media/scratch/Container_Build/HRK_CASA_6.5_DASK_WSC3.3.1024.simg python3 /data/2GC/APPLY_CALIB_SPLIT.py --MS_FILE=/data/${data_file} --WORK_DIR=/data/ --DOSPLIT --SPWD=${write_spwd}
