#!/bin/bash

# HRK MPIfR 2026
#
# usage like: source 02_OBS_DIAGNOSTIC_PLOTS MSFILENAME CURRENT_DIR
#

set -euo pipefail  # safer bash: exit on error, unset vars are errors

# Define the column to be plotted
#
PLTDATA = "DATA"


# Define MS dataset
DATA_FILE=$1

# Define the path of the current working directory
WORK_PATH=$3

# Define Container to use
CONTAINER_NAME="MKPLUSATEDGAR_SHADEMS.simg"

# Define path
#
# DATA_PATH="/bEDD/MPLUS-WORKONDATA/"
DATA_PATH=$2
CONT_PATH="/bEDD/MPLUS-CONTAINER/"


# Define singularity input 
#
CONTAINER="${CONT_PATH}/${CONTAINER_NAME}"
DATADIR="/data/"
WORKDIR="/work/"


# Execute shadems inside singularity
#
singularity exec --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} "${CONTAINER}" shadems --xaxis FREQ --yaxis "${PLTDATA}":amp --corr XX,YY --iter-corr --iter-field --dir "${WORKDIR}" "${DATADIR}${DATA_FILE}"

singularity exec --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} "${CONTAINER}" shadems --corr XX,YY --iter-corr  -x ANTENNA1 -y ANTENNA2 --cmap coolwarm --aaxis "${PLTDATA}":amp --ared mean --dir "${WORKDIR}" "${DATADIR}${DATA_FILE}"

singularity exec --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} "${CONTAINER}" shadems --corr XX,YY --iter-corr  -x ANTENNA1 -y ANTENNA2 --cmap coolwarm --aaxis "${PLTDATA}":amp --ared std --dir "${WORKDIR}" "${DATADIR}${DATA_FILE}"

singularity exec --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} "${CONTAINER}" shadems --xaxis FREQ --yaxis "${PLTDATA}":phase --corr XX,YY --iter-corr --iter-field --dir "${WORKDIR}" "${DATADIR}${DATA_FILE}"

singularity exec --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} "${CONTAINER}" shadems --corr XX,YY --iter-corr  -x ANTENNA1 -y ANTENNA2 --cmap coolwarm --aaxis "${PLTDATA}":phase --ared mean --dir "${WORKDIR}" "${DATADIR}${DATA_FILE}"

singularity exec --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} "${CONTAINER}" shadems --corr XX,YY --iter-corr  -x ANTENNA1 -y ANTENNA2 --cmap coolwarm --aaxis "${PLTDATA}":phase --ared std --dir "${WORKDIR}" "${DATADIR}${DATA_FILE}"
