#!/bin/bash

# HRK MPIfR 2026
#
# usage like: source 03_RUN_PYTHON_CASA MSFILENAME CURRENT_DIR
#
# IMPORTANT to note:
#
#         - in the working directory make a user directory
#                   mkdir -p ${USER}/.casa/data
#         - in running the singularity your need to bind homes to the current directiory  
#                   --bind ${WORK_PATH}:/homes
#

set -euo pipefail  # safer bash: exit on error, unset vars are errors

# Define MS dataset
DATA_FILE=$1

# Define the path of the current working directory
WORK_PATH=$2

# Define the path of the current working directory
FIELD_ID=$3

# Define Container to use
CONTAINER_NAME="MKPLUSATEDGAR.simg"

# Define path
#
# DATA_PATH="/bEDD/MPLUS-DATA/"
DATA_PATH="/bEDD/MPLUS-WORKONDATA/"
CONT_PATH="/bEDD/MPLUS-CONTAINER/"

# Define singularity input 
#
CONTAINER="${CONT_PATH}/${CONTAINER_NAME}"
DATADIR="/data/"
WORKDIR="/work/"


# Execute shadems inside singularity
#
singularity exec --bind ${WORK_PATH}:/homes --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} --env PYTHONPATH=${WORKDIR}DASKMSWERKZEUGKASTEN:/opt/venviron/py_venv/lib/python3.12.4/site-packages "${CONTAINER}" python3 ${WORKDIR}DASKMSWERKZEUGKASTEN/DYNAMIC_SPECTRUM_PLOTTER.py --MS_FILE=${DATADIR}${DATA_FILE} --WORK_DIR=${WORKDIR} --DOBSLWATERFALLSPEC --PLOTFILEMARKER=PREFG_FID_${FIELD_ID}_ --DONOTICKS --DOPLTSTDDATA --FIELD_ID=${FIELD_ID} --DO_SAVE_AVERAGE_DATA=PREFG_DATA_FID_${FIELD_ID}_


