universe        = vanilla
executable      = 04_FLAGGING_HRK
arguments       = $(DATA_FILE) $(CWD) $(FIELD_ID)
log             = condor_logs/run_example_$(Cluster)_$(Process).log
output          = condor_logs/run_example_$(Cluster)_$(Process).out
error           = condor_logs/run_example_$(Cluster)_$(Process).err
request_cpus    = 16
request_memory  = 128GB
request_disk    = 150GB
getenv          = True

queue 1
