#!/bin/bash
# HRK MPIfR 2026
#
#

set -euo pipefail  # safer bash: exit on error, unset vars are errors

# Define MS dataset
DATA_FILE=$1

# Define the path of the current working directory
WORK_PATH=$3

# Define Container to use
CONTAINER_NAME="MKPLUSATEDGAR.simg"

# Define path
#
#DATA_PATH="/bEDD/MPLUS-WORKONDATA/"
DATA_PATH=$2
CONT_PATH="/bEDD/MPLUS-CONTAINER/"

# json file name
#
JSON_FILE=$4

# field_id 
#
FIELD_ID=$5


# Define singularity input 
#
CONTAINER="${CONT_PATH}/${CONTAINER_NAME}"
DATADIR="/data/"
WORKDIR="/work/"


# Execute shadems inside singularity
#
singularity exec --bind ${WORK_PATH}:/homes --bind ${WORK_PATH}:${WORKDIR} --bind ${DATA_PATH}:${DATADIR} "${CONTAINER}" python3 ${WORKDIR}12_SPLIT_SOURCE.py ${DATA_FILE} ${DATADIR} ${WORKDIR} ${JSON_FILE} ${FIELD_ID}
